<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="office-PC" name="Default test" tests="3" failures="0" timestamp="20 Jul 2016 04:31:22 GMT" time="0.053" errors="0">
  <testcase name="@BeforeClass preConditions" time="0.0" classname="scripts.verifyNavigationLink">
    <failure type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at scripts.BaseTest.preConditions(BaseTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.NullPointerException
	... 29 more
]]>
    </failure>
  </testcase> <!-- @BeforeClass preConditions -->
  <testcase name="@AfterClass postCondition" time="0.0" classname="scripts.verifyNavigationLink">
    <skipped/>
  </testcase> <!-- @AfterClass postCondition -->
  <testcase name="testValidLoginLogout" time="0.002" classname="scripts.verifyNavigationLink">
    <skipped/>
  </testcase> <!-- testValidLoginLogout -->
  <testcase name="clickLogoutLink" time="0.002" classname="scripts.verifyNavigationLink">
    <skipped/>
  </testcase> <!-- clickLogoutLink -->
  <testcase name="testNavigation" time="0.003" classname="scripts.verifyNavigationLink">
    <skipped/>
  </testcase> <!-- testNavigation -->
</testsuite> <!-- Default test -->
